# Generated by Django 4.2.1 on 2023-05-17 17:56

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("dt_created", models.DateTimeField(auto_created=True)),
                ("body", models.TextField()),
                ("dt_updated", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "PENDING"), (2, "QUEUED"), (3, "ERROR"), (4, "SENT")]
                    ),
                ),
            ],
        ),
    ]
