# Generated by Django 4.2.1 on 2023-05-19 15:33

from django.db import migrations, models
import django.db.models.deletion
from django.db.migrations import RunPython


def create_initial_topics_and_channels(apps, schema_editor):
    Topic = apps.get_model("proxy", "Topic")
    Topic.objects.get_or_create(name="Sales", channel="slack")
    Topic.objects.get_or_create(name="Pricing", channel="email")


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "channel",
                    models.CharField(
                        choices=[("slack", "Slack"), ("email", "Email")], max_length=200
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("description", models.TextField()),
                ("dt_created", models.DateTimeField(auto_now_add=True)),
                ("dt_updated", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "PENDING"), (2, "QUEUED"), (3, "ERROR"), (4, "SENT")],
                        default=1,
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="proxy.topic"
                    ),
                ),
            ],
        ),
        RunPython(create_initial_topics_and_channels, RunPython.noop)
    ]
