# Generated by Django 4.2.1 on 2023-05-19 06:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("proxy", "0003_message_topic"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="channel",
            name="url",
        ),
    ]
