# Generated by Django 4.2.1 on 2023-05-19 06:20


from django.db import migrations
from django.db.migrations import RunPython


def create_initial_topics_and_channels(apps, schema_editor):
    Channel = apps.get_model("proxy", "Channel")
    Topic = apps.get_model("proxy", "Topic")
    slack, _ = Channel.objects.get_or_create(name="slack")
    email, _ = Channel.objects.get_or_create(name="email")
    Topic.objects.get_or_create(name="Sales", channel=slack)
    Topic.objects.get_or_create(name="Pricing", channel=email)


class Migration(migrations.Migration):
    dependencies = [
        ("proxy", "0004_remove_channel_url"),
    ]

    operations = [RunPython(create_initial_topics_and_channels, RunPython.noop)]
