# Generated by Django 4.2.1 on 2023-05-19 14:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proxy", "0006_rename_body_message_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topic",
            name="channel",
            field=models.CharField(
                choices=[("slack", "Slack"), ("email", "Email")], max_length=200
            ),
        ),
        migrations.DeleteModel(
            name="Channel",
        ),
    ]
